# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dNo8n_ycF-sfolXokjPP_IK1CcFBSsK1
"""

# Install necessary libraries
!pip install torch datasets transformers scikit-learn gradio nltk seaborn matplotlib

import torch
from torch.utils.data import Dataset
from datasets import load_dataset
from transformers import (
    BertTokenizer, BertForNextSentencePrediction,
    Trainer, TrainingArguments, EarlyStoppingCallback
)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import random
import nltk
from nltk.tokenize import sent_tokenize
import numpy as np

nltk.download('punkt')

# Load dataset
raw_dataset = load_dataset("wikitext", "wikitext-103-raw-v1", split="train[:5%]")

# Improved sentence pair creator
nltk.download('punkt_tab')
def create_sentence_pairs_better(dataset, max_pairs=3000):
    all_sentences = []
    for text in dataset['text']:
        lines = sent_tokenize(text)
        all_sentences.extend(lines)

    sentence_pairs = []
    for text in dataset['text']:
        lines = sent_tokenize(text)
        for i in range(len(lines) - 1):
            if len(lines[i].split()) > 5 and len(lines[i+1].split()) > 5:
                # Positive
                sentence_pairs.append((lines[i], lines[i+1], 0))
                # Negative
                while True:
                    sent2 = random.choice(all_sentences)
                    if sent2 not in lines:
                        break
                sentence_pairs.append((lines[i], sent2, 1))
            if len(sentence_pairs) >= max_pairs:
                return sentence_pairs
    return sentence_pairs

pairs = create_sentence_pairs_better(raw_dataset, max_pairs=3000)

#Train/val/test split
train_pairs, temp_pairs = train_test_split(pairs, test_size=0.2, random_state=42)
val_pairs, test_pairs = train_test_split(temp_pairs, test_size=0.5, random_state=42)

# Dataset class
class NSPDataset(Dataset):
    def __init__(self, pairs, tokenizer, max_len=128): # Changed _init_ to __init__
        self.examples = []
        for sent1, sent2, label in pairs:
            encoding = tokenizer(sent1, sent2, truncation=True, padding='max_length',
                                 max_length=max_len, return_tensors="pt")
            encoding = {k: v.squeeze() for k, v in encoding.items()}
            encoding['labels'] = torch.tensor(label)
            self.examples.append(encoding)

    def __len__(self): # Changed _len_ to __len__
        return len(self.examples)

    def __getitem__(self, idx): # Changed _getitem_ to __getitem__
        return self.examples[idx]

# Tokenizer and datasets
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
train_dataset = NSPDataset(train_pairs, tokenizer)
val_dataset = NSPDataset(val_pairs, tokenizer)
test_dataset = NSPDataset(test_pairs, tokenizer)

# Model
model = BertForNextSentencePrediction.from_pretrained("bert-base-uncased")

# Training args
training_args = TrainingArguments(
    output_dir="./results_bert",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none"
)

# Metrics function
def compute_metrics(pred):
    labels = pred.label_ids
    preds = np.argmax(pred.predictions, axis=1)
    return {"accuracy": accuracy_score(labels, preds)}

# Trainer with early stopping
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

# Train
print("Training BERT...")
trainer.train()

# Evaluate
print("Evaluating on test set...")
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Evaluate
preds = trainer_bert.predict(test_dataset)
y_true = preds.label_ids
y_pred = preds.predictions.argmax(axis=1)

# Print metrics
print("Accuracy:", accuracy_score(y_true, y_pred))
print("Classification Report:\n", classification_report(y_true, y_pred))

# Confusion matrix
sns.heatmap(confusion_matrix(y_true, y_pred), annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix (BERT NSP)")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gradio as gr
from transformers import BertTokenizer, BertForNextSentencePrediction, RobertaTokenizer, RobertaForSequenceClassification

# Initialize models and tokenizers (using pre-trained models)
bert_model = BertForNextSentencePrediction.from_pretrained("bert-base-uncased")
roberta_model = RobertaForSequenceClassification.from_pretrained("roberta-base", num_labels=2)
bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
roberta_tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

# Prediction function for BERT and RoBERTa with visualizations
def predict_nsp_ensemble(sent1, sent2):
    # BERT prediction
    inputs_bert = bert_tokenizer(sent1, sent2, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs_bert = bert_model(**inputs_bert)
        probs_bert = torch.softmax(outputs_bert.logits, dim=1)
        pred_bert = torch.argmax(probs_bert, dim=1).item()

    # RoBERTa prediction
    inputs_roberta = roberta_tokenizer(sent1, sent2, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs_roberta = roberta_model(**inputs_roberta)
        probs_roberta = torch.softmax(outputs_roberta.logits, dim=1)
        pred_roberta = torch.argmax(probs_roberta, dim=1).item()

    # Combine predictions (Majority vote: if BERT and RoBERTa agree, output that; otherwise, default to 1)
    final_pred = 0 if (pred_bert + pred_roberta) <= 1 else 1  # Majority vote (0 = Next, 1 = Not Next)

# Prediction function for BERT and RoBERTa with visualizations
def predict_nsp_ensemble(sent1, sent2):
    # BERT prediction
    inputs_bert = bert_tokenizer(sent1, sent2, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs_bert = bert_model(**inputs_bert)
        probs_bert = torch.softmax(outputs_bert.logits, dim=1)
        pred_bert = torch.argmax(probs_bert, dim=1).item()

    # RoBERTa prediction
    inputs_roberta = roberta_tokenizer(sent1, sent2, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs_roberta = roberta_model(**inputs_roberta)
        probs_roberta = torch.softmax(outputs_roberta.logits, dim=1)
        pred_roberta = torch.argmax(probs_roberta, dim=1).item()

    # Combine predictions (majority vote)
    final_pred = 0 if (pred_bert + pred_roberta) <= 1 else 1  # Majority vote (0 = Next, 1 = Not Next)

    # Visualize probabilities
    plt.figure(figsize=(8, 5))
    labels = ['Next', 'Not Next']
    bert_probs = probs_bert[0].cpu().numpy()
    roberta_probs = probs_roberta[0].cpu().numpy()

    # Bar chart for individual model probabilities
    x = np.arange(len(labels))
    width = 0.35
    fig, ax = plt.subplots()
    ax.bar(x - width/2, bert_probs, width, label='BERT', color='blue')
    ax.bar(x + width/2, roberta_probs, width, label='RoBERTa', color='orange')

    ax.set_ylabel('Probability')
    ax.set_title('BERT vs RoBERTa Prediction Probabilities')
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.legend()
    plt.tight_layout()
    plt.show()

    return f"Final Prediction: {'NEXT' if final_pred == 0 else 'NOT NEXT'} (BERT: {pred_bert}, RoBERTa: {pred_roberta})"

# Gradio Interface
def launch_gradio():
    gr.Interface(
        fn=predict_nsp_ensemble,
        inputs=[gr.Textbox(label="Sentence 1"), gr.Textbox(label="Sentence 2")],
        outputs="text",
        title="Next Sentence Prediction (BERT & RoBERTa Ensemble)",
        description="Predict whether two sentences follow each other logically using BERT and RoBERTa models combined. Visualization of predictions provided.",
        examples=[
            ["The sky is blue.", "The grass is green."],
            ["She went to the market.", "The sun was setting."]
        ]
    ).launch()

# Launch the Gradio interface
launch_gradio()



